const express = require('express');
const router = express.Router();
const restaurant = require("../controllers/restaurant");
router.post('/restaurentList', restaurant.restaurantList);
router.post('/favouriteRestaurant', restaurant.favouriteRestaurant);
router.post('/restaurentReviewRating', restaurant.restaurentReviewRating);
router.post('/addRestaurentReviewRating', restaurant.addRestaurentReviewRating);
router.post('/createOrder', restaurant.orders);
router.post('/createCard', restaurant.createCard);
router.post('/cardList', restaurant.cardList);
router.post('/favouriteMenuRestaurant', restaurant.favouriteMenuRestaurant);
router.get('/orderStatus', restaurant.orderStatus);
router.post('/createOrderProcessDetails', restaurant.createOrderProcessDetails);
router.post('/OrderProcessDetails', restaurant.OrderProcessDetails);
router.post('/pastOrders', restaurant.pastOrders);
router.post('/pendingOrders', restaurant.pendingOrders);
router.post('/cart', restaurant.cart);
router.post('/calculateTax', restaurant.calculateTax);
module.exports = router;